name: 'CI/CD'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install jshint --global

      - name: Run Linter
        run: |
          # Lint all JavaScript files in the giftlink-backend directory
          find ./giftlink-backend -name "*.js" -exec jshint {} +
          echo "Linted all the js files successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install client dependencies
        run: |
          cd giftlink-frontend
          npm install  # Install the frontend dependencies

      - name: Run build
        run: |
          cd giftlink-frontend
          npm run build  # Build the client
          echo "Client-side build successful"
